# Generated by Django 4.1.4 on 2023-12-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
