# Generated by Django 4.1.4 on 2023-12-23 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='review_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
