# Generated by Django 4.1.4 on 2023-12-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customuser_review_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=0.000819000819000819, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
