# Generated by Django 4.1.4 on 2023-12-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_customuser_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='average',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='best',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='worst',
            field=models.IntegerField(default=0),
        ),
    ]
