# Generated by Django 4.1.4 on 2023-12-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_teacher_average_alter_teacher_best_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(default=1111, max_length=4),
            preserve_default=False,
        ),
    ]
